# Generated by Django 3.2.18 on 2023-02-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
